-- Live Challenge tables for LearnTense
create table if not exists public.challenge_rooms (
  id bigint generated by default as identity primary key,
  host_id uuid not null references auth.users(id) on delete cascade,
  room_code text not null unique,
  topic text not null,
  question_count integer not null default 5 check (question_count between 1 and 50),
  status text not null default 'waiting' check (status in ('waiting','active','finished')),
  created_at timestamptz not null default now()
);

create table if not exists public.challenge_participants (
  room_id bigint not null references public.challenge_rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  score integer not null default 0,
  finished boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (room_id, user_id)
);

alter table public.challenge_rooms enable row level security;
alter table public.challenge_participants enable row level security;

drop policy if exists "challenge rooms readable by authenticated users" on public.challenge_rooms;
create policy "challenge rooms readable by authenticated users"
on public.challenge_rooms for select
to authenticated
using (true);

drop policy if exists "users can create their own challenge rooms" on public.challenge_rooms;
create policy "users can create their own challenge rooms"
on public.challenge_rooms for insert
to authenticated
with check (auth.uid() = host_id);

drop policy if exists "hosts can update their challenge rooms" on public.challenge_rooms;
create policy "hosts can update their challenge rooms"
on public.challenge_rooms for update
to authenticated
using (auth.uid() = host_id)
with check (auth.uid() = host_id);

drop policy if exists "challenge participants readable by authenticated users" on public.challenge_participants;
create policy "challenge participants readable by authenticated users"
on public.challenge_participants for select
to authenticated
using (true);

drop policy if exists "users can join challenges as themselves" on public.challenge_participants;
create policy "users can join challenges as themselves"
on public.challenge_participants for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users can update their challenge score" on public.challenge_participants;
create policy "users can update their challenge score"
on public.challenge_participants for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create index if not exists challenge_rooms_code_idx on public.challenge_rooms(room_code);
create index if not exists challenge_participants_room_idx on public.challenge_participants(room_id);
