-- LearnTense 2.0 Supabase schema
-- Compatible with an existing LearnTense database.
-- Safe to run from a fresh database OR one where tenses/questions already exist.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.tenses (
  id bigint primary key,
  name text not null unique
);

-- Upgrade an existing tenses table without deleting its data.
alter table public.tenses add column if not exists category text;
alter table public.tenses add column if not exists icon text;
alter table public.tenses add column if not exists description text;
alter table public.tenses add column if not exists sort_order integer;

update public.tenses set category = case
  when id between 1 and 4 then 'Present'
  when id between 5 and 8 then 'Past'
  when id between 9 and 12 then 'Future'
  else 'Present'
end where category is null;

update public.tenses set icon = case id
  when 1 then '🟢' when 2 then '🔵' when 3 then '🟣' when 4 then '🟠'
  when 5 then '🟢' when 6 then '🔵' when 7 then '🟣' when 8 then '🟠'
  when 9 then '🚀' when 10 then '⏳' when 11 then '🏆' when 12 then '⭐'
  else '📚' end where icon is null;

update public.tenses set sort_order = id::integer where sort_order is null;

update public.tenses set description = case id
  when 1 then 'Habits, routines and facts.'
  when 2 then 'Actions happening now or around now.'
  when 3 then 'Past actions connected to the present.'
  when 4 then 'Actions continuing over a period of time.'
  when 5 then 'Completed actions in the past.'
  when 6 then 'Actions in progress at a past time.'
  when 7 then 'An earlier action before another past action.'
  when 8 then 'An ongoing action before another past event.'
  when 9 then 'Predictions, promises and future actions.'
  when 10 then 'An action that will be in progress.'
  when 11 then 'An action completed before a future point.'
  when 12 then 'Duration continuing up to a future point.'
  else 'English tense practice.' end where description is null;

-- Add constraints only after existing rows have been populated.
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'tenses_category_check') then
    alter table public.tenses add constraint tenses_category_check check (category in ('Present','Past','Future'));
  end if;
end $$;

alter table public.tenses alter column category set not null;
alter table public.tenses alter column icon set not null;
alter table public.tenses alter column sort_order set not null;

create table if not exists public.lessons (
  id uuid primary key default gen_random_uuid(),
  tense_id bigint not null references public.tenses(id) on delete cascade,
  title text not null,
  content text not null,
  sort_order integer not null default 0
);

-- Existing questions tables are left intact. New installs use BIGINT ids.
create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  tense_id bigint not null references public.tenses(id) on delete cascade,
  question_type text not null default 'multiple_choice',
  question_text text not null,
  options jsonb not null default '[]'::jsonb,
  correct_answer integer not null default 0,
  explanation text,
  difficulty text not null default 'easy' check (difficulty in ('easy','medium','hard')),
  created_at timestamptz not null default now()
);

create table if not exists public.user_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  tense_id bigint not null references public.tenses(id) on delete cascade,
  questions_attempted integer not null default 0,
  correct_answers integer not null default 0,
  accuracy numeric(5,2) not null default 0,
  mastery numeric(5,2) not null default 0,
  last_practiced timestamptz,
  primary key (user_id, tense_id)
);

create table if not exists public.attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint references public.questions(id) on delete set null,
  tense_id bigint references public.tenses(id) on delete set null,
  selected_answer integer,
  correct boolean not null,
  time_taken integer,
  created_at timestamptz not null default now()
);

create table if not exists public.mistakes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint references public.questions(id) on delete cascade,
  tense_id bigint references public.tenses(id) on delete cascade,
  reviewed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.achievements (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  achievement_key text not null,
  unlocked_at timestamptz not null default now(),
  unique (user_id, achievement_key)
);

-- RLS
alter table public.profiles enable row level security;
alter table public.tenses enable row level security;
alter table public.lessons enable row level security;
alter table public.questions enable row level security;
alter table public.user_progress enable row level security;
alter table public.attempts enable row level security;
alter table public.mistakes enable row level security;
alter table public.achievements enable row level security;

drop policy if exists "public read tenses" on public.tenses;
create policy "public read tenses" on public.tenses for select using (true);
drop policy if exists "public read lessons" on public.lessons;
create policy "public read lessons" on public.lessons for select using (true);
drop policy if exists "public read questions" on public.questions;
create policy "public read questions" on public.questions for select using (true);

drop policy if exists "users read own profile" on public.profiles;
create policy "users read own profile" on public.profiles for select using (auth.uid() = id);
drop policy if exists "users insert own profile" on public.profiles;
create policy "users insert own profile" on public.profiles for insert with check (auth.uid() = id);
drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile" on public.profiles for update using (auth.uid() = id);

drop policy if exists "users read own progress" on public.user_progress;
create policy "users read own progress" on public.user_progress for select using (auth.uid() = user_id);
drop policy if exists "users insert own progress" on public.user_progress;
create policy "users insert own progress" on public.user_progress for insert with check (auth.uid() = user_id);
drop policy if exists "users update own progress" on public.user_progress;
create policy "users update own progress" on public.user_progress for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "users read own attempts" on public.attempts;
create policy "users read own attempts" on public.attempts for select using (auth.uid() = user_id);
drop policy if exists "users insert own attempts" on public.attempts;
create policy "users insert own attempts" on public.attempts for insert with check (auth.uid() = user_id);

drop policy if exists "users read own mistakes" on public.mistakes;
create policy "users read own mistakes" on public.mistakes for select using (auth.uid() = user_id);
drop policy if exists "users insert own mistakes" on public.mistakes;
create policy "users insert own mistakes" on public.mistakes for insert with check (auth.uid() = user_id);
drop policy if exists "users update own mistakes" on public.mistakes;
create policy "users update own mistakes" on public.mistakes for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "users read own achievements" on public.achievements;
create policy "users read own achievements" on public.achievements for select using (auth.uid() = user_id);
drop policy if exists "users insert own achievements" on public.achievements;
create policy "users insert own achievements" on public.achievements for insert with check (auth.uid() = user_id);

-- Seed/update the 12 tenses.
insert into public.tenses (id,name,category,icon,description,sort_order) values
(1,'Simple Present','Present','🟢','Habits, routines and facts.',1),
(2,'Present Continuous','Present','🔵','Actions happening now or around now.',2),
(3,'Present Perfect','Present','🟣','Past actions connected to the present.',3),
(4,'Present Perfect Continuous','Present','🟠','Actions continuing over a period of time.',4),
(5,'Simple Past','Past','🟢','Completed actions in the past.',5),
(6,'Past Continuous','Past','🔵','Actions in progress at a past time.',6),
(7,'Past Perfect','Past','🟣','An earlier action before another past action.',7),
(8,'Past Perfect Continuous','Past','🟠','An ongoing action before another past event.',8),
(9,'Simple Future','Future','🚀','Predictions, promises and future actions.',9),
(10,'Future Continuous','Future','⏳','An action that will be in progress.',10),
(11,'Future Perfect','Future','🏆','An action completed before a future point.',11),
(12,'Future Perfect Continuous','Future','⭐','Duration continuing up to a future point.',12)
on conflict (id) do update set name=excluded.name, category=excluded.category, icon=excluded.icon, description=excluded.description, sort_order=excluded.sort_order;

-- Starter questions. Duplicate question text is ignored.
insert into public.questions (tense_id, question_type, question_text, options, correct_answer, explanation, difficulty)
select * from (values
(1::bigint,'multiple_choice','She ___ to school every day.','["go","goes","going","gone"]'::jsonb,1,'With he, she or it in the Simple Present, the verb normally takes -s or -es.','easy'),
(1::bigint,'multiple_choice','Which sentence is correct?','["They plays football.","They play football.","They playing football.","They played every day."]'::jsonb,1,'They is plural, so use the base verb: They play.','easy'),
(1::bigint,'multiple_choice','Which sentence describes a routine?','["I am eating now.","I ate yesterday.","I walk to school every day.","I will eat later."]'::jsonb,2,'Repeated habits and routines are commonly expressed with the Simple Present.','easy'),
(2::bigint,'multiple_choice','Look! The baby ___.','["cries","is crying","cried","has cried"]'::jsonb,1,'An action happening now uses the Present Continuous: is + verb-ing.','easy'),
(3::bigint,'multiple_choice','They ___ their homework.','["have finished","finish yesterday","are finish","has finished"]'::jsonb,0,'Present Perfect uses have/has + past participle. They takes have.','easy')
) as seed(tense_id,question_type,question_text,options,correct_answer,explanation,difficulty)
where not exists (select 1 from public.questions q where q.tense_id=seed.tense_id and q.question_text=seed.question_text);
