const LESSONS={
1:{when:['Habits and routines','Facts and general truths','Repeated actions'],structure:'Subject + base verb; he/she/it + verb-s/-es',signal:'always, usually, every day, often',examples:[['I walk to school every day.','Routine'],['She watches TV in the evening.','Habit'],['Water boils at 100°C.','Fact']],mistakes:[['She play tennis.','She plays tennis.'],['He go to work every day.','He goes to work every day.']]},
2:{when:['Actions happening now','Temporary situations','Changing situations'],structure:'Subject + am/is/are + verb-ing',signal:'now, right now, at the moment, today',examples:[['I am reading a book now.','Happening now'],['They are studying English this week.','Temporary situation'],['The weather is getting warmer.','Changing situation']],mistakes:[['She is read a book.','She is reading a book.'],['They are play football.','They are playing football.']]},
3:{when:['Past actions connected to now','Life experiences','Recent actions with present results'],structure:'Subject + have/has + past participle',signal:'already, just, yet, ever, never, since, for',examples:[['I have visited Delhi.','Experience'],['She has just finished her work.','Recent result'],['Have you ever seen snow?','Experience']],mistakes:[['She have finished.','She has finished.'],['I have went there.','I have gone there.']]},
4:{when:['Actions that started in the past and continue','Emphasis on duration or activity'],structure:'Subject + have/has been + verb-ing',signal:'for, since, all day, lately, recently',examples:[['I have been studying for two hours.','Duration'],['She has been working here since 2022.','Continuing action'],['They have been waiting all morning.','Ongoing activity']],mistakes:[['He has been work all day.','He has been working all day.'],['They have been wait since noon.','They have been waiting since noon.']]},
5:{when:['Completed actions in the past','A sequence of past events','Past actions with a finished time'],structure:'Subject + past form of the verb',signal:'yesterday, last week, ago, in 2020',examples:[['I visited Delhi last year.','Finished past action'],['She watched a movie yesterday.','Finished time'],['They played football on Sunday.','Completed event']],mistakes:[['I go yesterday.','I went yesterday.'],['She did went home.','She went home.']]},
6:{when:['An action in progress at a past time','Background actions','Two actions happening at the same time'],structure:'Subject + was/were + verb-ing',signal:'while, when, at 8 pm yesterday',examples:[['I was reading at 8 pm.','Action in progress'],['They were playing when it rained.','Background action'],['She was cooking while he was studying.','Simultaneous actions']],mistakes:[['They was playing.','They were playing.'],['I was read a book.','I was reading a book.']]},
7:{when:['An action completed before another past action','Showing which past event happened first'],structure:'Subject + had + past participle',signal:'before, after, by the time, already',examples:[['I had finished before he arrived.','Earlier past action'],['She had left when I called.','Earlier event'],['By noon, they had completed the work.','Completed before a past point']],mistakes:[['She had went home.','She had gone home.'],['They had finish before lunch.','They had finished before lunch.']]},
8:{when:['An ongoing action before another past event','Emphasizing duration before a past point'],structure:'Subject + had been + verb-ing',signal:'for, since, before, when',examples:[['I had been studying for two hours when she called.','Duration'],['They had been waiting since noon before the bus arrived.','Ongoing activity'],['She was tired because she had been working all day.','Cause and duration']],mistakes:[['He had been work all day.','He had been working all day.'],['They had been waited for an hour.','They had been waiting for an hour.']]},
9:{when:['Predictions','Promises and decisions made now','Future facts or intentions'],structure:'Subject + will + base verb',signal:'tomorrow, next week, soon, I think, probably',examples:[['I will call you tomorrow.','Future action'],['I think it will rain.','Prediction'],['She will help us.','Promise']],mistakes:[['I will goes tomorrow.','I will go tomorrow.'],['She will to study.','She will study.']]},
10:{when:['An action that will be in progress at a future time','Expected ongoing activities'],structure:'Subject + will be + verb-ing',signal:'this time tomorrow, at 8 pm tomorrow, next week',examples:[['I will be studying at 8 pm.','Future activity'],['They will be travelling this time tomorrow.','Future action in progress'],['She will be working next Monday.','Expected activity']],mistakes:[['I will be study at 8.','I will be studying at 8.'],['They will be travelling?','They will be travelling.']]},
11:{when:['An action completed before a future time','Deadlines and future completion'],structure:'Subject + will have + past participle',signal:'by, by the time, before + future point',examples:[['I will have finished by Friday.','Future deadline'],['She will have arrived by noon.','Completed before future point'],['They will have completed the project by June.','Future completion']],mistakes:[['I will have finish by Friday.','I will have finished by Friday.'],['She will has arrived.','She will have arrived.']]},
12:{when:['Duration continuing up to a future point','Emphasizing how long an action will have continued'],structure:'Subject + will have been + verb-ing',signal:'for, since, by the time, by next year',examples:[['By June, I will have been working here for five years.','Duration'],['She will have been studying for three hours by 9 pm.','Future duration'],['By next month, they will have been living here for a year.','Continuing duration']],mistakes:[['I will have been work for years.','I will have been working for years.'],['She will has been studying.','She will have been studying.']]}
};
const oldStartLesson=window.startLesson;
window.startLesson=function(id){
 currentTense=tenses.find(t=>t.id===id)||fallbackTenses.find(t=>t.id===id)||fallbackTenses[0];
 localStorage.setItem('lastTense',id);showScreen('lesson');
 const d=LESSONS[id]||LESSONS[1],m=mastery(id);
 $('lessonCard').innerHTML=`<span class="badge">${currentTense.category} Tense</span><h1>${currentTense.icon} ${currentTense.name}</h1><p class="muted">${currentTense.description}</p><div class="rule"><h2>📖 When to use it</h2><ul>${d.when.map(x=>`<li>${x}</li>`).join('')}</ul><p class="formula"><strong>Structure:</strong> ${d.structure}</p><p><strong>Common signal words:</strong> ${d.signal}</p></div><h2>💬 Examples</h2>${d.examples.map(x=>`<div class="example"><strong>${x[1]}</strong><br>${x[0]}</div>`).join('')}<div class="rule"><h2>⚠️ Common mistakes</h2>${d.mistakes.map(x=>`<div class="example"><span>❌ ${x[0]}</span><br><strong>✅ ${x[1]}</strong></div>`).join('')}</div><div class="feedback"><strong>🎯 Your mastery: ${m}%</strong><br><span class="muted">Practice this tense to improve your mastery.</span></div><button class="primary" style="margin-top:18px;width:100%" onclick="startQuiz(${id})">Start ${currentTense.name} practice →</button>`;
};
(function(){const s=document.createElement('script');s.src='js/simple-present-quiz.js';s.defer=false;document.body.appendChild(s)})();